# Hexo blog configuration file for 404 Blog Not Found
# subtitle:    # Removed empty subtitle field for clarity

title: 404 Blog Not Found
subtitle:
description: Learn by doing, not by reading.
keywords: blog, programming, learning, technology
author: Ian Tsien
language: en
timezone: Asia/Hong_Kong
url: https://ian-tsien.github.io/404BlogNotFound/
root: /404BlogNotFound/
permalink: ':category/:post_title/'
pretty_urls:
  trailing_index: false
  trailing_html: false
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
# skip_render: []   # Uncomment and specify files/patterns to skip rendering if needed
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''
default_category: uncategorized
tag_map: null
# tag_map:   # Uncomment and provide mappings if needed, or leave commented out if not used
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
archive_generator:
  per_page: 20
  yearly: true
  monthly: true
category_generator:
  per_page: 10
tag_generator:
  per_page: 10
include: []
exclude: []
ignore: []
theme: icarus
marked:
  gfm: true
  breaks: true
  smartLists: true
  smartypants: false
  pedantic: false
  mangle: false
# className: Used to exclude items from gallery display
className: not-gallery-item
githubEmojis:
  enable: true           # 是否启用插件
  className: github-emoji  # 自定义表情的 CSS 类名
  unicode: false         # 是否将表情转为 Unicode 字符
  styles:                # 可选，内联样式
    display: inline
    margin: 0 2px
    height: 1.2em
    vertical-align: -0.1em